import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFAF0',
    padding: 20,
  },
  profileImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  logoContainer: {
    alignItems: 'center',
  },
  logo: {
    width: 200, // Ajuste o tamanho da logo conforme necessário
    height: 200, // Ajuste o tamanho da logo conforme necessário
    
  },
  bottomMenu: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    backgroundColor: '#FF6F61',
    paddingVertical: 10,
  },
  menuItem: {
    fontSize: 16,
    color: '#4682B4',
    fontFamily: 'Comic Sans MS',
  },
  scoreContainer: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    width: '80%',
  },
  scoreText: {
    fontSize: 20,
    marginBottom: 20,
    fontFamily: 'Comic Sans MS',
  },
  progressBar: {
    width: '100%',
    height: 20,
    backgroundColor: '#E0E0E0',
    borderRadius: 10,
    overflow: 'hidden',
    marginBottom: 20,
  },
  progress: {
    height: '100%',
    backgroundColor: '#FF6F61',
  },
  rewardImage: {
    width: 100,
    height: 100,
    marginTop: 20,
  },
  parentalControlContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#C9EAEF',
    padding: 20,
  },
  parentalControlTitle: {
    fontSize: 28,
    marginBottom: 20,
    color: '#333333',
    fontFamily: 'Comic Sans MS',
  },
  parentalControlInput: {
    width: '80%',
    height: 40,
    borderColor: '#A0A0A0',
    borderWidth: 1,
    borderRadius: 15,
    marginBottom: 15,
    paddingHorizontal: 15,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    fontSize: 18,
    fontFamily: 'Comic Sans MS',
  },
  parentalControlSwitchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  parentalControlListItem: {
    fontSize: 16,
    padding: 10,
    backgroundColor: '#48c0ca',
    borderBottomWidth: 1,
    borderBottomColor: '#cccccc',
    width: '80%',
    textAlign: 'center',
    borderRadius: 10,
  },

  formContainer: {
    width: '100%',
    maxWidth: 400,
    alignItems: 'center', // Center elements inside the form
    padding: 20,
    backgroundColor: '#f9f9f9',
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  title: {
    fontFamily: 'Comic Sans MS',
    fontSize: 28,
    color: '#FF6347',
    textShadowColor: '#000000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
    fontWeight: 'bold',
    textAlign: 'center',
    marginVertical: 20,
  },
  input: {
    width: '80%',
    height: 50,
    borderColor: '#FF6347',
    borderWidth: 1,
    borderRadius: 25,
    marginBottom: 15,
    paddingHorizontal: 15,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    fontSize: 18,
    fontFamily: 'Comic Sans MS',
  },
  button: {
    backgroundColor: '#FF6347',
    paddingVertical: 15,
    paddingHorizontal: 25,
    borderRadius: 25,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    width: '80%', // Ensure button takes up same width as input
    alignItems: 'center', // Center text inside the button
  },
  buttonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    fontFamily: 'Comic Sans MS',
  },
  btnCadastro: {
    backgroundColor: '#007BFF',
  },
  toggleText: {
    marginTop: 20,
    textDecorationLine: 'underline',
    color: '#4682B4',
    fontSize: 16,
    fontFamily: 'Comic Sans MS',
  },
  errorText: {
    color: '#FF6347',
    fontFamily: 'Comic Sans MS',
    marginBottom: 10,
  },
});

export default styles;
